# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSPJ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSPJ

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Firestore'

  target 'IOSPJTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
